---
title: "Inferring directionality for rule-based models built from gene expression data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r block1, echo = T, results = 'hide', message=FALSE, warning=FALSE}
library(R.ROSETTA)
library(igraph)

# gene expression data
out_jon <- rosetta(autcon)
g = graph.data.frame(as.data.frame(do.call(rbind, strsplit(unique(out_jon$main$features[which(out_jon$main$pValue<0.001)]),","))))
g = simplify(g)

# the assumption: outdegree > indegree, in gene expression data
# indegree of our graph
ind = degree(g, v = V(g), mode = c("in"),
       loops = FALSE)

# outdegree of our graph
oud = degree(g, v = V(g), mode = c("out"),
       loops = FALSE)
```

```{r block2, echo=T}
# average indegree of nodes in the graph
mean(ind[ind>0])
# normalized average indegree of nodes in the graph
mean(ind)/length(ind[ind>0])

# average outdegree of nodes in the graph
mean(oud[oud>0])
# normalized average outdegree of nodes in the graph
mean(oud)/length(oud[oud>0])
```

```{r block3, echo=T, warning=FALSE}
plot(g, layout=layout_as_tree, edge.arrow.size=0.5,vertex.label=NA)

plot.igraph(g,vertex.size=6,edge.arrow.size=0.5,vertex.label=NA,
            layout=layout.fruchterman.reingold(g, niter=10000))
```

